-- MySQL Script generated by MySQL Workbench
-- Thu Jul 29 19:13:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cineVision` DEFAULT CHARACTER SET utf8 ;
USE `cineVision` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  estado tinyint default 1,
  PRIMARY KEY (`idUsuarios`)
  )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Privilegios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Privilegios` (
  `idPrivilegios` INT NOT NULL AUTO_INCREMENT,
  `descPrivilegio` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrivilegios`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarioPrivilegios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarioPrivilegios` (
  `idusuarioPrivilegios` INT NOT NULL AUTO_INCREMENT,
  `fkUsuario` INT NOT NULL,
  `fkPrivilegio` INT NOT NULL,
  PRIMARY KEY (`idusuarioPrivilegios`)
)ENGINE = InnoDB;
  
ALTER TABLE `usuarioPrivilegios`
  ADD CONSTRAINT `fk_UserP` FOREIGN KEY (`fkUsuario`) 
  REFERENCES `Usuarios` (`idUsuarios`);
  
ALTER TABLE `usuarioPrivilegios`
  ADD CONSTRAINT `fk_PrivP` FOREIGN KEY (`fkPrivilegio`) 
  REFERENCES `Privilegios` (`idPrivilegios`);
  
-- -----------------------------------------------------
-- Table `mydb`.`Peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Peliculas` (
  `idPeliculas` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Clasificación` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `Subtitulado` VARCHAR(45) NULL,
  `Idioma` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  PRIMARY KEY (`idPeliculas`)
  )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Cines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cines` (
  `idCines` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Dirección` VARCHAR(45) NULL,
  PRIMARY KEY (`idCines`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Salas` (
  `idSalas` INT NOT NULL AUTO_INCREMENT,
  `fkCine` INT NOT NULL,
  `Descripción` VARCHAR(100) NULL,
  `formatoPeli` VARCHAR(45) NULL,
  `puntos` INT NULL,
  `precioSala` DOUBLE NULL,
  PRIMARY KEY (`idSalas`)
  )
ENGINE = InnoDB;
  
ALTER TABLE `Salas`
  ADD CONSTRAINT `fk_cinS` FOREIGN KEY (`fkCine`) 
  REFERENCES `Cines` (`idCines`);
  

-- -----------------------------------------------------
-- Table `mydb`.`horarioCine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarioCine` (
  `idhorarioCine` INT NOT NULL AUTO_INCREMENT,
  `fkPelicula` INT NULL,
  `fkSala` INT NOT NULL,
  `fechaHorario` TIMESTAMP NULL,
  PRIMARY KEY (`idhorarioCine`)
)
ENGINE = InnoDB;

ALTER TABLE `horarioCine`
  ADD CONSTRAINT `fkhcinP` FOREIGN KEY (`fkPelicula`) 
  REFERENCES `Peliculas` (`idPeliculas`);
ALTER TABLE `horarioCine`
  ADD CONSTRAINT `fkhcinSa` FOREIGN KEY (`fkSala`) 
  REFERENCES `Salas` (`idSalas`);
-- -----------------------------------------------------
-- Table `mydb`.`Derechos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Derechos` (
  `idDerechos` INT NOT NULL AUTO_INCREMENT,
  `fkPelicula` INT NOT NULL,
  `estadoDerechos` TINYINT NULL,
  PRIMARY KEY (`idDerechos`)
  )
ENGINE = InnoDB;

-- drop table derechos;

ALTER TABLE `Derechos`
  ADD CONSTRAINT `fkpder` FOREIGN KEY (`fkPelicula`) 
  REFERENCES `Peliculas` (`idPeliculas`);
-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Nit` VARCHAR(45) NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Asientos` (
  `idAsientos` INT NOT NULL AUTO_INCREMENT,
  `fkSala` INT NOT NULL,
  `Fila` INT NULL,
  `Columna` VARCHAR(45) NULL,
  PRIMARY KEY (`idAsientos`)
  )
ENGINE = InnoDB;

-- drop table Asientos;

ALTER TABLE `Asientos`
  ADD CONSTRAINT `fkasieS` FOREIGN KEY (`fkSala`) 
  REFERENCES `Salas` (`idSalas`);
-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `fkCliente` INT NULL,
  `metodoPago` VARCHAR(45) NULL,
  `subTotal` DOUBLE NULL,
  `impuesto` DOUBLE NULL,
  PRIMARY KEY (`idFactura`)
)
ENGINE = InnoDB;

ALTER TABLE `Factura`
  ADD CONSTRAINT `fkfacCl` FOREIGN KEY (`fkCliente`) 
  REFERENCES `Clientes` (`idClientes`);

-- -----------------------------------------------------
-- Table `mydb`.`Reservaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reservaciones` (
  `idReservaciones` INT NOT NULL AUTO_INCREMENT,
  `fkAsientos` INT NOT NULL,
  `subTotalAsiento` DOUBLE NULL,
  `fkFactura` INT NULL,
  PRIMARY KEY (`idReservaciones`)
  )
ENGINE = InnoDB;
  
ALTER TABLE `Reservaciones`
  ADD CONSTRAINT `fkresas` FOREIGN KEY (`fkAsientos`) 
  REFERENCES `Asientos` (`idAsientos`);
  
ALTER TABLE `Reservaciones`
  ADD CONSTRAINT `fkresfac` FOREIGN KEY (`fkFactura`) 
  REFERENCES `Factura` (`idFactura`);
  
-- -----------------------------------------------------
-- Table `mydb`.`registroPuntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registroPuntos` (
  `idregistroPuntos` INT NOT NULL AUTO_INCREMENT,
  `fkCliente` INT NOT NULL,
  `puntosAcum` INT NULL,
  `puntosUsados` INT NULL,
  PRIMARY KEY (`idregistroPuntos`)
  )
ENGINE = InnoDB;
  
--  drop table registroPuntos;
  
ALTER TABLE `registroPuntos`
  ADD CONSTRAINT `fkregCl` FOREIGN KEY (`fkCliente`) 
  REFERENCES `Clientes` (`idClientes`);  


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
